library(tidyverse)
library(magrittr)
load("/home/john/fantasy-football/data/points_adp_draft.Rda")

## Need to build lags for each observation. 


## We have 8 seasons of cost data so we can have 7 lags of draft cost.

model_data <-
  points_adp_draft %>%
  arrange(player,year) %>%
  group_by(player) %>%
  mutate(lag_value1 = case_when(lag(year,1) == year - 1 ~ lag(adj_value,1),
                                TRUE ~ NA_real_),
         lag_value2 = case_when(lag(year,1) == year - 2 ~ lag(adj_value,1),
                                lag(year,2) == year - 2 ~ lag(adj_value,2),
                                TRUE ~ NA_real_),
         lag_value3 = case_when(lag(year,1) == year - 3 ~ lag(adj_value,1),
                                lag(year,2) == year - 3 ~ lag(adj_value,2),
                                lag(year,3) == year - 3 ~ lag(adj_value,3),
                                TRUE ~ NA_real_),
         lag_value4 = case_when(lag(year,1) == year - 4 ~ lag(adj_value,1),
                                lag(year,2) == year - 4 ~ lag(adj_value,2),
                                lag(year,3) == year - 4 ~ lag(adj_value,3),
                                lag(year,4) == year - 4 ~ lag(adj_value,4),
                                TRUE ~ NA_real_),
         lag_value5 = case_when(lag(year,1) == year - 5 ~ lag(adj_value,1),
                                lag(year,2) == year - 5 ~ lag(adj_value,2),
                                lag(year,3) == year - 5 ~ lag(adj_value,3),
                                lag(year,4) == year - 5 ~ lag(adj_value,4),
                                lag(year,5) == year - 5 ~ lag(adj_value,5),
                                TRUE ~ NA_real_),
         lag_value6 = case_when(lag(year,1) == year - 6 ~ lag(adj_value,1),
                                lag(year,2) == year - 6 ~ lag(adj_value,2),
                                lag(year,3) == year - 6 ~ lag(adj_value,3),
                                lag(year,4) == year - 6 ~ lag(adj_value,4),
                                lag(year,5) == year - 6 ~ lag(adj_value,5),
                                lag(year,6) == year - 6 ~ lag(adj_value,6),
                                TRUE ~ NA_real_),
         lag_value7 = case_when(lag(year,1) == year - 7 ~ lag(adj_value,1),
                                lag(year,2) == year - 7 ~ lag(adj_value,2),
                                lag(year,3) == year - 7 ~ lag(adj_value,3),
                                lag(year,4) == year - 7 ~ lag(adj_value,4),
                                lag(year,5) == year - 7 ~ lag(adj_value,5),
                                lag(year,6) == year - 7 ~ lag(adj_value,6),
                                lag(year,7) == year - 7 ~ lag(adj_value,7),
                                TRUE ~ NA_real_)) %>%
        ## The first keeper was in 2011, so 2012 was the first year being kept could appear in a lag. 
        ## So there are up to six keeper lags to select.
  mutate(lag_keeper1 = case_when(lag(year,1) == year - 1 ~ lag(keeper,1),
                                 TRUE ~ NA_real_),
         lag_keeper2 = case_when(lag(year,1) == year - 2 ~ lag(keeper,1),
                                 lag(year,2) == year - 2 ~ lag(keeper,2),
                                 TRUE ~ NA_real_),
         lag_keeper3 = case_when(lag(year,1) == year - 3 ~ lag(keeper,1),
                                 lag(year,2) == year - 3 ~ lag(keeper,2),
                                 lag(year,3) == year - 3 ~ lag(keeper,3),
                                 TRUE ~ NA_real_),
         lag_keeper4 = case_when(lag(year,1) == year - 4 ~ lag(keeper,1),
                                 lag(year,2) == year - 4 ~ lag(keeper,2),
                                 lag(year,3) == year - 4 ~ lag(keeper,3),
                                 lag(year,4) == year - 4 ~ lag(keeper,4),
                                 TRUE ~ NA_real_),
         lag_keeper5 = case_when(lag(year,1) == year - 5 ~ lag(keeper,1),
                                 lag(year,2) == year - 5 ~ lag(keeper,2),
                                 lag(year,3) == year - 5 ~ lag(keeper,3),
                                 lag(year,4) == year - 5 ~ lag(keeper,4),
                                 lag(year,5) == year - 5 ~ lag(keeper,5),
                                 TRUE ~ NA_real_),
         lag_keeper6 = case_when(lag(year,1) == year - 6 ~ lag(keeper,1),
                                 lag(year,2) == year - 6 ~ lag(keeper,2),
                                 lag(year,3) == year - 6 ~ lag(keeper,3),
                                 lag(year,4) == year - 6 ~ lag(keeper,4),
                                 lag(year,5) == year - 6 ~ lag(keeper,5),
                                 lag(year,6) == year - 6 ~ lag(keeper,6),
                                 TRUE ~ NA_real_)) %>%
         ## ADP data goes back to 2007, so we have up to eleven lags. 
         ## There are lags for both overall ADP and position ADP
  mutate(lag_overall1 = case_when(lag(year,1) == year - 1 ~ lag(overall,1),
                                      TRUE ~ NA_real_),
         lag_overall2 = case_when(lag(year,1) == year - 2 ~ lag(overall,1),
                                      lag(year,2) == year - 2 ~ lag(overall,2),
                                      TRUE ~ NA_real_),
         lag_overall3 = case_when(lag(year,1) == year - 3 ~ lag(overall,1),
                                      lag(year,2) == year - 3 ~ lag(overall,2),
                                      lag(year,3) == year - 3 ~ lag(overall,3),
                                      TRUE ~ NA_real_),
         lag_overall4 = case_when(lag(year,1) == year - 4 ~ lag(overall,1),
                                      lag(year,2) == year - 4 ~ lag(overall,2),
                                      lag(year,3) == year - 4 ~ lag(overall,3),
                                      lag(year,4) == year - 4 ~ lag(overall,4),
                                      TRUE ~ NA_real_),
         lag_overall5 = case_when(lag(year,1) == year - 5 ~ lag(overall,1),
                                      lag(year,2) == year - 5 ~ lag(overall,2),
                                      lag(year,3) == year - 5 ~ lag(overall,3),
                                      lag(year,4) == year - 5 ~ lag(overall,4),
                                      lag(year,5) == year - 5 ~ lag(overall,5),
                                      TRUE ~ NA_real_),
         lag_overall6 = case_when(lag(year,1) == year - 6 ~ lag(overall,1),
                                      lag(year,2) == year - 6 ~ lag(overall,2),
                                      lag(year,3) == year - 6 ~ lag(overall,3),
                                      lag(year,4) == year - 6 ~ lag(overall,4),
                                      lag(year,5) == year - 6 ~ lag(overall,5),
                                      lag(year,6) == year - 6 ~ lag(overall,6),
                                      TRUE ~ NA_real_),
         lag_overall7 = case_when(lag(year,1) == year - 7 ~ lag(overall,1),
                                      lag(year,2) == year - 7 ~ lag(overall,2),
                                      lag(year,3) == year - 7 ~ lag(overall,3),
                                      lag(year,4) == year - 7 ~ lag(overall,4),
                                      lag(year,5) == year - 7 ~ lag(overall,5),
                                      lag(year,6) == year - 7 ~ lag(overall,6),
                                      lag(year,7) == year - 7 ~ lag(overall,7),
                                      TRUE ~ NA_real_),
         lag_overall8 = case_when(lag(year,1) == year - 8 ~ lag(overall,1),
                                      lag(year,2) == year - 8 ~ lag(overall,2),
                                      lag(year,3) == year - 8 ~ lag(overall,3),
                                      lag(year,4) == year - 8 ~ lag(overall,4),
                                      lag(year,5) == year - 8 ~ lag(overall,5),
                                      lag(year,6) == year - 8 ~ lag(overall,6),
                                      lag(year,7) == year - 8 ~ lag(overall,7),
                                      lag(year,8) == year - 8 ~ lag(overall,8),
                                      TRUE ~ NA_real_),
         lag_overall9 = case_when(lag(year,1) == year - 9 ~ lag(overall,1),
                                      lag(year,2) == year - 9 ~ lag(overall,2),
                                      lag(year,3) == year - 9 ~ lag(overall,3),
                                      lag(year,4) == year - 9 ~ lag(overall,4),
                                      lag(year,5) == year - 9 ~ lag(overall,5),
                                      lag(year,6) == year - 9 ~ lag(overall,6),
                                      lag(year,7) == year - 9 ~ lag(overall,7),
                                      lag(year,8) == year - 9 ~ lag(overall,8),
                                      lag(year,9) == year - 9 ~ lag(overall,9),
                                      TRUE ~ NA_real_),
         lag_overall10 = case_when( lag(year,1) == year - 10 ~ lag(overall,1),
                                        lag(year,2) == year - 10 ~ lag(overall,2),
                                        lag(year,3) == year - 10 ~ lag(overall,3),
                                        lag(year,4) == year - 10 ~ lag(overall,4),
                                        lag(year,5) == year - 10 ~ lag(overall,5),
                                        lag(year,6) == year - 10 ~ lag(overall,6),
                                        lag(year,7) == year - 10 ~ lag(overall,7),
                                        lag(year,8) == year - 10 ~ lag(overall,8),
                                        lag(year,9) == year - 10 ~ lag(overall,9),
                                        lag(year,10) == year - 10 ~ lag(overall,10),
                                        TRUE ~ NA_real_)) %>%
  mutate(lag_overall_adp1 = case_when(lag(year,1) == year - 1 ~ lag(overall_adp,1),
                                      TRUE ~ as.integer(NA_real_)),
         lag_overall_adp2 = case_when(lag(year,1) == year - 2 ~ lag(overall_adp,1),
                                      lag(year,2) == year - 2 ~ lag(overall_adp,2),
                                      TRUE ~ as.integer(NA_real_)),
         lag_overall_adp3 = case_when(lag(year,1) == year - 3 ~ lag(overall_adp,1),
                                      lag(year,2) == year - 3 ~ lag(overall_adp,2),
                                      lag(year,3) == year - 3 ~ lag(overall_adp,3),
                                      TRUE ~ as.integer(NA_real_)),
         lag_overall_adp4 = case_when(lag(year,1) == year - 4 ~ lag(overall_adp,1),
                                      lag(year,2) == year - 4 ~ lag(overall_adp,2),
                                      lag(year,3) == year - 4 ~ lag(overall_adp,3),
                                      lag(year,4) == year - 4 ~ lag(overall_adp,4),
                                      TRUE ~ as.integer(NA_real_)),
         lag_overall_adp5 = case_when(lag(year,1) == year - 5 ~ lag(overall_adp,1),
                                      lag(year,2) == year - 5 ~ lag(overall_adp,2),
                                      lag(year,3) == year - 5 ~ lag(overall_adp,3),
                                      lag(year,4) == year - 5 ~ lag(overall_adp,4),
                                      lag(year,5) == year - 5 ~ lag(overall_adp,5),
                                      TRUE ~ as.integer(NA_real_)),
         lag_overall_adp6 = case_when(lag(year,1) == year - 6 ~ lag(overall_adp,1),
                                      lag(year,2) == year - 6 ~ lag(overall_adp,2),
                                      lag(year,3) == year - 6 ~ lag(overall_adp,3),
                                      lag(year,4) == year - 6 ~ lag(overall_adp,4),
                                      lag(year,5) == year - 6 ~ lag(overall_adp,5),
                                      lag(year,6) == year - 6 ~ lag(overall_adp,6),
                                      TRUE ~ as.integer(NA_real_)),
         lag_overall_adp7 = case_when(lag(year,1) == year - 7 ~ lag(overall_adp,1),
                                      lag(year,2) == year - 7 ~ lag(overall_adp,2),
                                      lag(year,3) == year - 7 ~ lag(overall_adp,3),
                                      lag(year,4) == year - 7 ~ lag(overall_adp,4),
                                      lag(year,5) == year - 7 ~ lag(overall_adp,5),
                                      lag(year,6) == year - 7 ~ lag(overall_adp,6),
                                      lag(year,7) == year - 7 ~ lag(overall_adp,7),
                                      TRUE ~ as.integer(NA_real_)),
        lag_overall_adp8 = case_when(lag(year,1) == year - 8 ~ lag(overall_adp,1),
                                     lag(year,2) == year - 8 ~ lag(overall_adp,2),
                                     lag(year,3) == year - 8 ~ lag(overall_adp,3),
                                     lag(year,4) == year - 8 ~ lag(overall_adp,4),
                                     lag(year,5) == year - 8 ~ lag(overall_adp,5),
                                     lag(year,6) == year - 8 ~ lag(overall_adp,6),
                                     lag(year,7) == year - 8 ~ lag(overall_adp,7),
                                     lag(year,8) == year - 8 ~ lag(overall_adp,8),
                                     TRUE ~ as.integer(NA_real_)),
        lag_overall_adp9 = case_when(lag(year,1) == year - 9 ~ lag(overall_adp,1),
                                     lag(year,2) == year - 9 ~ lag(overall_adp,2),
                                     lag(year,3) == year - 9 ~ lag(overall_adp,3),
                                     lag(year,4) == year - 9 ~ lag(overall_adp,4),
                                     lag(year,5) == year - 9 ~ lag(overall_adp,5),
                                     lag(year,6) == year - 9 ~ lag(overall_adp,6),
                                     lag(year,7) == year - 9 ~ lag(overall_adp,7),
                                     lag(year,8) == year - 9 ~ lag(overall_adp,8),
                                     lag(year,9) == year - 9 ~ lag(overall_adp,9),
                                     TRUE ~ as.integer(NA_real_)),
        lag_overall_adp10 = case_when( lag(year,1) == year - 10 ~ lag(overall_adp,1),
                                       lag(year,2) == year - 10 ~ lag(overall_adp,2),
                                       lag(year,3) == year - 10 ~ lag(overall_adp,3),
                                       lag(year,4) == year - 10 ~ lag(overall_adp,4),
                                       lag(year,5) == year - 10 ~ lag(overall_adp,5),
                                       lag(year,6) == year - 10 ~ lag(overall_adp,6),
                                       lag(year,7) == year - 10 ~ lag(overall_adp,7),
                                       lag(year,8) == year - 10 ~ lag(overall_adp,8),
                                       lag(year,9) == year - 10 ~ lag(overall_adp,9),
                                      lag(year,10) == year - 10 ~ lag(overall_adp,10),
                                      TRUE ~ as.integer(NA_real_))) %>%
      # Now repeat for position adp
  mutate(lag_pos_adp1 = case_when(lag(year,1) == year - 1 ~ lag(pos_adp,1),
                                      TRUE ~ as.integer(NA_real_)),
         lag_pos_adp2 = case_when(lag(year,1) == year - 2 ~ lag(pos_adp,1),
                                      lag(year,2) == year - 2 ~ lag(pos_adp,2),
                                      TRUE ~ as.integer(NA_real_)),
         lag_pos_adp3 = case_when(lag(year,1) == year - 3 ~ lag(pos_adp,1),
                                      lag(year,2) == year - 3 ~ lag(pos_adp,2),
                                      lag(year,3) == year - 3 ~ lag(pos_adp,3),
                                      TRUE ~ as.integer(NA_real_)),
         lag_pos_adp4 = case_when(lag(year,1) == year - 4 ~ lag(pos_adp,1),
                                      lag(year,2) == year - 4 ~ lag(pos_adp,2),
                                      lag(year,3) == year - 4 ~ lag(pos_adp,3),
                                      lag(year,4) == year - 4 ~ lag(pos_adp,4),
                                      TRUE ~ as.integer(NA_real_)),
         lag_pos_adp5 = case_when(lag(year,1) == year - 5 ~ lag(pos_adp,1),
                                      lag(year,2) == year - 5 ~ lag(pos_adp,2),
                                      lag(year,3) == year - 5 ~ lag(pos_adp,3),
                                      lag(year,4) == year - 5 ~ lag(pos_adp,4),
                                      lag(year,5) == year - 5 ~ lag(pos_adp,5),
                                      TRUE ~ as.integer(NA_real_)),
         lag_pos_adp6 = case_when(lag(year,1) == year - 6 ~ lag(pos_adp,1),
                                      lag(year,2) == year - 6 ~ lag(pos_adp,2),
                                      lag(year,3) == year - 6 ~ lag(pos_adp,3),
                                      lag(year,4) == year - 6 ~ lag(pos_adp,4),
                                      lag(year,5) == year - 6 ~ lag(pos_adp,5),
                                      lag(year,6) == year - 6 ~ lag(pos_adp,6),
                                      TRUE ~ as.integer(NA_real_)),
         lag_pos_adp7 = case_when(lag(year,1) == year - 7 ~ lag(pos_adp,1),
                                      lag(year,2) == year - 7 ~ lag(pos_adp,2),
                                      lag(year,3) == year - 7 ~ lag(pos_adp,3),
                                      lag(year,4) == year - 7 ~ lag(pos_adp,4),
                                      lag(year,5) == year - 7 ~ lag(pos_adp,5),
                                      lag(year,6) == year - 7 ~ lag(pos_adp,6),
                                      lag(year,7) == year - 7 ~ lag(pos_adp,7),
                                      TRUE ~ as.integer(NA_real_)),
         lag_pos_adp8 = case_when(lag(year,1) == year - 8 ~ lag(pos_adp,1),
                                      lag(year,2) == year - 8 ~ lag(pos_adp,2),
                                      lag(year,3) == year - 8 ~ lag(pos_adp,3),
                                      lag(year,4) == year - 8 ~ lag(pos_adp,4),
                                      lag(year,5) == year - 8 ~ lag(pos_adp,5),
                                      lag(year,6) == year - 8 ~ lag(pos_adp,6),
                                      lag(year,7) == year - 8 ~ lag(pos_adp,7),
                                      lag(year,8) == year - 8 ~ lag(pos_adp,8),
                                      TRUE ~ as.integer(NA_real_)),
         lag_pos_adp9 = case_when(lag(year,1) == year - 9 ~ lag(pos_adp,1),
                                      lag(year,2) == year - 9 ~ lag(pos_adp,2),
                                      lag(year,3) == year - 9 ~ lag(pos_adp,3),
                                      lag(year,4) == year - 9 ~ lag(pos_adp,4),
                                      lag(year,5) == year - 9 ~ lag(pos_adp,5),
                                      lag(year,6) == year - 9 ~ lag(pos_adp,6),
                                      lag(year,7) == year - 9 ~ lag(pos_adp,7),
                                      lag(year,8) == year - 9 ~ lag(pos_adp,8),
                                      lag(year,9) == year - 9 ~ lag(pos_adp,9),
                                      TRUE ~ as.integer(NA_real_)),
         lag_pos_adp10 = case_when( lag(year,1) == year - 10 ~ lag(pos_adp,1),
                                        lag(year,2) == year - 10 ~ lag(pos_adp,2),
                                        lag(year,3) == year - 10 ~ lag(pos_adp,3),
                                        lag(year,4) == year - 10 ~ lag(pos_adp,4),
                                        lag(year,5) == year - 10 ~ lag(pos_adp,5),
                                        lag(year,6) == year - 10 ~ lag(pos_adp,6),
                                        lag(year,7) == year - 10 ~ lag(pos_adp,7),
                                        lag(year,8) == year - 10 ~ lag(pos_adp,8),
                                        lag(year,9) == year - 10 ~ lag(pos_adp,9),
                                        lag(year,10) == year - 10 ~ lag(pos_adp,10),
                                        TRUE ~ as.integer(NA_real_))) %>%
          ## Now for points. We can do average points as well as total season points (through 16 games)
          ## They aren't necessarily the same, if a player doesn't play then that doesn't count as part of the denominator.
          ## There are 17 lags to calculate
  mutate(lag_ppg1 = case_when(lag(year,1) == year - 1 ~ lag(ppg,1),
                                  TRUE ~ NA_real_),
         lag_ppg2 = case_when(lag(year,1) == year - 2 ~ lag(ppg,1),
                                  lag(year,2) == year - 2 ~ lag(ppg,2),
                                  TRUE ~ NA_real_),
         lag_ppg3 = case_when(lag(year,1) == year - 3 ~ lag(ppg,1),
                                  lag(year,2) == year - 3 ~ lag(ppg,2),
                                  lag(year,3) == year - 3 ~ lag(ppg,3),
                                  TRUE ~ NA_real_),
         lag_ppg4 = case_when(lag(year,1) == year - 4 ~ lag(ppg,1),
                                  lag(year,2) == year - 4 ~ lag(ppg,2),
                                  lag(year,3) == year - 4 ~ lag(ppg,3),
                                  lag(year,4) == year - 4 ~ lag(ppg,4),
                                  TRUE ~ NA_real_),
         lag_ppg5 = case_when(lag(year,1) == year - 5 ~ lag(ppg,1),
                                  lag(year,2) == year - 5 ~ lag(ppg,2),
                                  lag(year,3) == year - 5 ~ lag(ppg,3),
                                  lag(year,4) == year - 5 ~ lag(ppg,4),
                                  lag(year,5) == year - 5 ~ lag(ppg,5),
                                  TRUE ~ NA_real_),
         lag_ppg6 = case_when(lag(year,1) == year - 6 ~ lag(ppg,1),
                                  lag(year,2) == year - 6 ~ lag(ppg,2),
                                  lag(year,3) == year - 6 ~ lag(ppg,3),
                                  lag(year,4) == year - 6 ~ lag(ppg,4),
                                  lag(year,5) == year - 6 ~ lag(ppg,5),
                                  lag(year,6) == year - 6 ~ lag(ppg,6),
                                  TRUE ~ NA_real_),
         lag_ppg7 = case_when(lag(year,1) == year - 7 ~ lag(ppg,1),
                                  lag(year,2) == year - 7 ~ lag(ppg,2),
                                  lag(year,3) == year - 7 ~ lag(ppg,3),
                                  lag(year,4) == year - 7 ~ lag(ppg,4),
                                  lag(year,5) == year - 7 ~ lag(ppg,5),
                                  lag(year,6) == year - 7 ~ lag(ppg,6),
                                  lag(year,7) == year - 7 ~ lag(ppg,7),
                                  TRUE ~ NA_real_),
         lag_ppg8 = case_when(lag(year,1) == year - 8 ~ lag(ppg,1),
                                  lag(year,2) == year - 8 ~ lag(ppg,2),
                                  lag(year,3) == year - 8 ~ lag(ppg,3),
                                  lag(year,4) == year - 8 ~ lag(ppg,4),
                                  lag(year,5) == year - 8 ~ lag(ppg,5),
                                  lag(year,6) == year - 8 ~ lag(ppg,6),
                                  lag(year,7) == year - 8 ~ lag(ppg,7),
                                  lag(year,8) == year - 8 ~ lag(ppg,8),
                                  TRUE ~ NA_real_),
         lag_ppg9 = case_when(lag(year,1) == year - 9 ~ lag(ppg,1),
                                  lag(year,2) == year - 9 ~ lag(ppg,2),
                                  lag(year,3) == year - 9 ~ lag(ppg,3),
                                  lag(year,4) == year - 9 ~ lag(ppg,4),
                                  lag(year,5) == year - 9 ~ lag(ppg,5),
                                  lag(year,6) == year - 9 ~ lag(ppg,6),
                                  lag(year,7) == year - 9 ~ lag(ppg,7),
                                  lag(year,8) == year - 9 ~ lag(ppg,8),
                                  lag(year,9) == year - 9 ~ lag(ppg,9),
                                  TRUE ~ NA_real_),
         lag_ppg10 = case_when( lag(year,1) == year - 10 ~ lag(ppg,1),
                                    lag(year,2) == year - 10 ~ lag(ppg,2),
                                    lag(year,3) == year - 10 ~ lag(ppg,3),
                                    lag(year,4) == year - 10 ~ lag(ppg,4),
                                    lag(year,5) == year - 10 ~ lag(ppg,5),
                                    lag(year,6) == year - 10 ~ lag(ppg,6),
                                    lag(year,7) == year - 10 ~ lag(ppg,7),
                                    lag(year,8) == year - 10 ~ lag(ppg,8),
                                    lag(year,9) == year - 10 ~ lag(ppg,9),
                                    lag(year,10) == year - 10 ~ lag(ppg,10),
                                    TRUE ~ NA_real_),
         
         lag_ppg11 = case_when( lag(year,1) == year - 11 ~ lag(ppg,1),
                                lag(year,2) == year - 11 ~ lag(ppg,2),
                                lag(year,3) == year - 11 ~ lag(ppg,3),
                                lag(year,4) == year - 11 ~ lag(ppg,4),
                                lag(year,5) == year - 11 ~ lag(ppg,5),
                                lag(year,6) == year - 11 ~ lag(ppg,6),
                                lag(year,7) == year - 11 ~ lag(ppg,7),
                                lag(year,8) == year - 11 ~ lag(ppg,8),
                                lag(year,9) == year - 11 ~ lag(ppg,9),
                                lag(year,10) == year - 11 ~ lag(ppg,10),
                                lag(year,11) == year - 11 ~ lag(ppg,11),
                                TRUE ~ NA_real_),
         lag_ppg12 = case_when( lag(year,1) == year - 12 ~ lag(ppg,1),
                                lag(year,2) == year - 12 ~ lag(ppg,2),
                                lag(year,3) == year - 12 ~ lag(ppg,3),
                                lag(year,4) == year - 12 ~ lag(ppg,4),
                                lag(year,5) == year - 12 ~ lag(ppg,5),
                                lag(year,6) == year - 12 ~ lag(ppg,6),
                                lag(year,7) == year - 12 ~ lag(ppg,7),
                                lag(year,8) == year - 12 ~ lag(ppg,8),
                                lag(year,9) == year - 12 ~ lag(ppg,9),
                                lag(year,10) == year - 12 ~ lag(ppg,10),
                                lag(year,11) == year - 12 ~ lag(ppg,11),
                                lag(year,12) == year - 12 ~ lag(ppg,12),
                                TRUE ~ NA_real_),
         lag_ppg13 = case_when( lag(year,1) == year - 13 ~ lag(ppg,1),
                                lag(year,2) == year - 13 ~ lag(ppg,2),
                                lag(year,3) == year - 13 ~ lag(ppg,3),
                                lag(year,4) == year - 13 ~ lag(ppg,4),
                                lag(year,5) == year - 13 ~ lag(ppg,5),
                                lag(year,6) == year - 13 ~ lag(ppg,6),
                                lag(year,7) == year - 13 ~ lag(ppg,7),
                                lag(year,8) == year - 13 ~ lag(ppg,8),
                                lag(year,9) == year - 13 ~ lag(ppg,9),
                                lag(year,10) == year - 13 ~ lag(ppg,10),
                                lag(year,11) == year - 13 ~ lag(ppg,11),
                                lag(year,12) == year - 13 ~ lag(ppg,12),
                                lag(year,13) == year - 13 ~ lag(ppg,13),
                                TRUE ~ NA_real_),
         lag_ppg14 = case_when( lag(year,1) == year - 14 ~ lag(ppg,1),
                                lag(year,2) == year - 14 ~ lag(ppg,2),
                                lag(year,3) == year - 14 ~ lag(ppg,3),
                                lag(year,4) == year - 14 ~ lag(ppg,4),
                                lag(year,5) == year - 14 ~ lag(ppg,5),
                                lag(year,6) == year - 14 ~ lag(ppg,6),
                                lag(year,7) == year - 14 ~ lag(ppg,7),
                                lag(year,8) == year - 14 ~ lag(ppg,8),
                                lag(year,9) == year - 14 ~ lag(ppg,9),
                                lag(year,10) == year - 14 ~ lag(ppg,10),
                                lag(year,11) == year - 14 ~ lag(ppg,11),
                                lag(year,12) == year - 14 ~ lag(ppg,12),
                                lag(year,13) == year - 14 ~ lag(ppg,13),
                                lag(year,14) == year - 14 ~ lag(ppg,14),
                                TRUE ~ NA_real_),
         lag_ppg15 = case_when( lag(year,1) == year - 15 ~ lag(ppg,1),
                                lag(year,2) == year - 15 ~ lag(ppg,2),
                                lag(year,3) == year - 15 ~ lag(ppg,3),
                                lag(year,4) == year - 15 ~ lag(ppg,4),
                                lag(year,5) == year - 15 ~ lag(ppg,5),
                                lag(year,6) == year - 15 ~ lag(ppg,6),
                                lag(year,7) == year - 15 ~ lag(ppg,7),
                                lag(year,8) == year - 15 ~ lag(ppg,8),
                                lag(year,9) == year - 15 ~ lag(ppg,9),
                                lag(year,10) == year - 15 ~ lag(ppg,10),
                                lag(year,11) == year - 15 ~ lag(ppg,11),
                                lag(year,12) == year - 15 ~ lag(ppg,12),
                                lag(year,13) == year - 15 ~ lag(ppg,13),
                                lag(year,14) == year - 15 ~ lag(ppg,14),
                                lag(year,15) == year - 15 ~ lag(ppg,15),
                                TRUE ~ NA_real_),
         lag_ppg16 = case_when( lag(year,1) == year - 16 ~ lag(ppg,1),
                                lag(year,2) == year - 16 ~ lag(ppg,2),
                                lag(year,3) == year - 16 ~ lag(ppg,3),
                                lag(year,4) == year - 16 ~ lag(ppg,4),
                                lag(year,5) == year - 16 ~ lag(ppg,5),
                                lag(year,6) == year - 16 ~ lag(ppg,6),
                                lag(year,7) == year - 16 ~ lag(ppg,7),
                                lag(year,8) == year - 16 ~ lag(ppg,8),
                                lag(year,9) == year - 16 ~ lag(ppg,9),
                                lag(year,10) == year - 16 ~ lag(ppg,10),
                                lag(year,11) == year - 16 ~ lag(ppg,11),
                                lag(year,12) == year - 16 ~ lag(ppg,12),
                                lag(year,13) == year - 16 ~ lag(ppg,13),
                                lag(year,14) == year - 16 ~ lag(ppg,14),
                                lag(year,15) == year - 16 ~ lag(ppg,15),
                                lag(year,16) == year - 16 ~ lag(ppg,16),
                                TRUE ~ NA_real_),
          lag_ppg17 = case_when( lag(year,1) == year - 17 ~ lag(ppg,1),
                                lag(year,2) == year - 17 ~ lag(ppg,2),
                                lag(year,3) == year - 17 ~ lag(ppg,3),
                                lag(year,4) == year - 17 ~ lag(ppg,4),
                                lag(year,5) == year - 17 ~ lag(ppg,5),
                                lag(year,6) == year - 17 ~ lag(ppg,6),
                                lag(year,7) == year - 17 ~ lag(ppg,7),
                                lag(year,8) == year - 17 ~ lag(ppg,8),
                                lag(year,9) == year - 17 ~ lag(ppg,9),
                                lag(year,10) == year - 17 ~ lag(ppg,10),
                                lag(year,11) == year - 17 ~ lag(ppg,11),
                                lag(year,12) == year - 17 ~ lag(ppg,12),
                                lag(year,13) == year - 17 ~ lag(ppg,13),
                                lag(year,14) == year - 17 ~ lag(ppg,14),
                                lag(year,15) == year - 17 ~ lag(ppg,15),
                                lag(year,16) == year - 17 ~ lag(ppg,16),
                                lag(year,17) == year - 17 ~ lag(ppg,17),
                                TRUE ~ NA_real_)) %>%
  mutate(lag_season_points1 = case_when(lag(year,1) == year - 1 ~ lag(season_points,1),
                                        TRUE ~ NA_real_),
         lag_season_points2 = case_when(lag(year,1) == year - 2 ~ lag(season_points,1),
                                        lag(year,2) == year - 2 ~ lag(season_points,2),
                                        TRUE ~ NA_real_),
         lag_season_points3 = case_when(lag(year,1) == year - 3 ~ lag(season_points,1),
                                        lag(year,2) == year - 3 ~ lag(season_points,2),
                                        lag(year,3) == year - 3 ~ lag(season_points,3),
                                        TRUE ~ NA_real_),
         lag_season_points4 = case_when(lag(year,1) == year - 4 ~ lag(season_points,1),
                                        lag(year,2) == year - 4 ~ lag(season_points,2),
                                        lag(year,3) == year - 4 ~ lag(season_points,3),
                                        lag(year,4) == year - 4 ~ lag(season_points,4),
                                        TRUE ~ NA_real_),
         lag_season_points5 = case_when(lag(year,1) == year - 5 ~ lag(season_points,1),
                                        lag(year,2) == year - 5 ~ lag(season_points,2),
                                        lag(year,3) == year - 5 ~ lag(season_points,3),
                                        lag(year,4) == year - 5 ~ lag(season_points,4),
                                        lag(year,5) == year - 5 ~ lag(season_points,5),
                                        TRUE ~ NA_real_),
         lag_season_points6 = case_when(lag(year,1) == year - 6 ~ lag(season_points,1),
                                        lag(year,2) == year - 6 ~ lag(season_points,2),
                                        lag(year,3) == year - 6 ~ lag(season_points,3),
                                        lag(year,4) == year - 6 ~ lag(season_points,4),
                                        lag(year,5) == year - 6 ~ lag(season_points,5),
                                        lag(year,6) == year - 6 ~ lag(season_points,6),
                                        TRUE ~ NA_real_),
         lag_season_points7 = case_when(lag(year,1) == year - 7 ~ lag(season_points,1),
                                         lag(year,2) == year - 7 ~ lag(season_points,2),
                                     lag(year,3) == year - 7 ~ lag(season_points,3),
                                     lag(year,4) == year - 7 ~ lag(season_points,4),
                                     lag(year,5) == year - 7 ~ lag(season_points,5),
                                     lag(year,6) == year - 7 ~ lag(season_points,6),
                                     lag(year,7) == year - 7 ~ lag(season_points,7),
                                     TRUE ~ NA_real_),
         lag_season_points8 = case_when(lag(year,1) == year - 8 ~ lag(season_points,1),
                                     lag(year,2) == year - 8 ~ lag(season_points,2),
                                     lag(year,3) == year - 8 ~ lag(season_points,3),
                                     lag(year,4) == year - 8 ~ lag(season_points,4),
                                     lag(year,5) == year - 8 ~ lag(season_points,5),
                                     lag(year,6) == year - 8 ~ lag(season_points,6),
                                     lag(year,7) == year - 8 ~ lag(season_points,7),
                                     lag(year,8) == year - 8 ~ lag(season_points,8),
                                     TRUE ~ NA_real_),
         lag_season_points9 = case_when(lag(year,1) == year - 9 ~ lag(season_points,1),
                                     lag(year,2) == year - 9 ~ lag(season_points,2),
                                     lag(year,3) == year - 9 ~ lag(season_points,3),
                                     lag(year,4) == year - 9 ~ lag(season_points,4),
                                     lag(year,5) == year - 9 ~ lag(season_points,5),
                                     lag(year,6) == year - 9 ~ lag(season_points,6),
                                     lag(year,7) == year - 9 ~ lag(season_points,7),
                                     lag(year,8) == year - 9 ~ lag(season_points,8),
                                     lag(year,9) == year - 9 ~ lag(season_points,9),
                                     TRUE ~ NA_real_),
         lag_season_points10 = case_when( lag(year,1) == year - 10 ~ lag(season_points,1),
                                       lag(year,2) == year - 10 ~ lag(season_points,2),
                                       lag(year,3) == year - 10 ~ lag(season_points,3),
                                       lag(year,4) == year - 10 ~ lag(season_points,4),
                                       lag(year,5) == year - 10 ~ lag(season_points,5),
                                       lag(year,6) == year - 10 ~ lag(season_points,6),
                                       lag(year,7) == year - 10 ~ lag(season_points,7),
                                       lag(year,8) == year - 10 ~ lag(season_points,8),
                                       lag(year,9) == year - 10 ~ lag(season_points,9),
                                       lag(year,10) == year - 10 ~ lag(season_points,10),
                                       TRUE ~ NA_real_),
                
         lag_season_points11 = case_when( lag(year,1) == year - 11 ~ lag(season_points,1),
                                       lag(year,2) == year - 11 ~ lag(season_points,2),
                                       lag(year,3) == year - 11 ~ lag(season_points,3),
                                       lag(year,4) == year - 11 ~ lag(season_points,4),
                                       lag(year,5) == year - 11 ~ lag(season_points,5),
                                       lag(year,6) == year - 11 ~ lag(season_points,6),
                                       lag(year,7) == year - 11 ~ lag(season_points,7),
                                       lag(year,8) == year - 11 ~ lag(season_points,8),
                                       lag(year,9) == year - 11 ~ lag(season_points,9),
                                       lag(year,10) == year - 11 ~ lag(season_points,10),
                                       lag(year,11) == year - 11 ~ lag(season_points,11),
                                       TRUE ~ NA_real_),
         lag_season_points12 = case_when( lag(year,1) == year - 12 ~ lag(season_points,1),
                                       lag(year,2) == year - 12 ~ lag(season_points,2),
                                       lag(year,3) == year - 12 ~ lag(season_points,3),
                                       lag(year,4) == year - 12 ~ lag(season_points,4),
                                       lag(year,5) == year - 12 ~ lag(season_points,5),
                                       lag(year,6) == year - 12 ~ lag(season_points,6),
                                       lag(year,7) == year - 12 ~ lag(season_points,7),
                                       lag(year,8) == year - 12 ~ lag(season_points,8),
                                       lag(year,9) == year - 12 ~ lag(season_points,9),
                                       lag(year,10) == year - 12 ~ lag(season_points,10),
                                       lag(year,11) == year - 12 ~ lag(season_points,11),
                                       lag(year,12) == year - 12 ~ lag(season_points,12),
                                       TRUE ~ NA_real_),
         lag_season_points13 = case_when( lag(year,1) == year - 13 ~ lag(season_points,1),
                                       lag(year,2) == year - 13 ~ lag(season_points,2),
                                       lag(year,3) == year - 13 ~ lag(season_points,3),
                                       lag(year,4) == year - 13 ~ lag(season_points,4),
                                       lag(year,5) == year - 13 ~ lag(season_points,5),
                                       lag(year,6) == year - 13 ~ lag(season_points,6),
                                       lag(year,7) == year - 13 ~ lag(season_points,7),
                                       lag(year,8) == year - 13 ~ lag(season_points,8),
                                       lag(year,9) == year - 13 ~ lag(season_points,9),
                                       lag(year,10) == year - 13 ~ lag(season_points,10),
                                       lag(year,11) == year - 13 ~ lag(season_points,11),
                                       lag(year,12) == year - 13 ~ lag(season_points,12),
                                       lag(year,13) == year - 13 ~ lag(season_points,13),
                                       TRUE ~ NA_real_),
         lag_season_points14 = case_when( lag(year,1) == year - 14 ~ lag(season_points,1),
                                       lag(year,2) == year - 14 ~ lag(season_points,2),
                                       lag(year,3) == year - 14 ~ lag(season_points,3),
                                       lag(year,4) == year - 14 ~ lag(season_points,4),
                                       lag(year,5) == year - 14 ~ lag(season_points,5),
                                       lag(year,6) == year - 14 ~ lag(season_points,6),
                                       lag(year,7) == year - 14 ~ lag(season_points,7),
                                       lag(year,8) == year - 14 ~ lag(season_points,8),
                                       lag(year,9) == year - 14 ~ lag(season_points,9),
                                       lag(year,10) == year - 14 ~ lag(season_points,10),
                                       lag(year,11) == year - 14 ~ lag(season_points,11),
                                       lag(year,12) == year - 14 ~ lag(season_points,12),
                                       lag(year,13) == year - 14 ~ lag(season_points,13),
                                       lag(year,14) == year - 14 ~ lag(season_points,14),
                                       TRUE ~ NA_real_),
         lag_season_points15 = case_when( lag(year,1) == year - 15 ~ lag(season_points,1),
                                       lag(year,2) == year - 15 ~ lag(season_points,2),
                                       lag(year,3) == year - 15 ~ lag(season_points,3),
                                       lag(year,4) == year - 15 ~ lag(season_points,4),
                                       lag(year,5) == year - 15 ~ lag(season_points,5),
                                       lag(year,6) == year - 15 ~ lag(season_points,6),
                                       lag(year,7) == year - 15 ~ lag(season_points,7),
                                       lag(year,8) == year - 15 ~ lag(season_points,8),
                                       lag(year,9) == year - 15 ~ lag(season_points,9),
                                       lag(year,10) == year - 15 ~ lag(season_points,10),
                                       lag(year,11) == year - 15 ~ lag(season_points,11),
                                       lag(year,12) == year - 15 ~ lag(season_points,12),
                                       lag(year,13) == year - 15 ~ lag(season_points,13),
                                       lag(year,14) == year - 15 ~ lag(season_points,14),
                                       lag(year,15) == year - 15 ~ lag(season_points,15),
                                       TRUE ~ NA_real_),
         lag_season_points16 = case_when( lag(year,1) == year - 16 ~ lag(season_points,1),
                                       lag(year,2) == year - 16 ~ lag(season_points,2),
                                       lag(year,3) == year - 16 ~ lag(season_points,3),
                                       lag(year,4) == year - 16 ~ lag(season_points,4),
                                       lag(year,5) == year - 16 ~ lag(season_points,5),
                                       lag(year,6) == year - 16 ~ lag(season_points,6),
                                       lag(year,7) == year - 16 ~ lag(season_points,7),
                                       lag(year,8) == year - 16 ~ lag(season_points,8),
                                       lag(year,9) == year - 16 ~ lag(season_points,9),
                                       lag(year,10) == year - 16 ~ lag(season_points,10),
                                       lag(year,11) == year - 16 ~ lag(season_points,11),
                                       lag(year,12) == year - 16 ~ lag(season_points,12),
                                       lag(year,13) == year - 16 ~ lag(season_points,13),
                                       lag(year,14) == year - 16 ~ lag(season_points,14),
                                       lag(year,15) == year - 16 ~ lag(season_points,15),
                                       lag(year,16) == year - 16 ~ lag(season_points,16),
                                       TRUE ~ NA_real_),
         lag_season_points17 = case_when( lag(year,1) == year - 17 ~ lag(season_points,1),
                                       lag(year,2) == year - 17 ~ lag(season_points,2),
                                       lag(year,3) == year - 17 ~ lag(season_points,3),
                                       lag(year,4) == year - 17 ~ lag(season_points,4),
                                       lag(year,5) == year - 17 ~ lag(season_points,5),
                                       lag(year,6) == year - 17 ~ lag(season_points,6),
                                       lag(year,7) == year - 17 ~ lag(season_points,7),
                                       lag(year,8) == year - 17 ~ lag(season_points,8),
                                       lag(year,9) == year - 17 ~ lag(season_points,9),
                                       lag(year,10) == year - 17 ~ lag(season_points,10),
                                       lag(year,11) == year - 17 ~ lag(season_points,11),
                                       lag(year,12) == year - 17 ~ lag(season_points,12),
                                       lag(year,13) == year - 17 ~ lag(season_points,13),
                                       lag(year,14) == year - 17 ~ lag(season_points,14),
                                       lag(year,15) == year - 17 ~ lag(season_points,15),
                                       lag(year,16) == year - 17 ~ lag(season_points,16),
                                       lag(year,17) == year - 17 ~ lag(season_points,17),
                                       TRUE ~ NA_real_)) %>%
  filter(keeper == 0,
         is.na(adj_value) == FALSE)

sum(draft_data$keeper)

1376 + 160

model_data %<>%
  select()
         
        
lapply(model_data,function(x)  sum(is.na(x))/length(x))  

# Season points -> 8 lags
# ppg - > 8 lags
# pos adp 4 lags
# overall adp 4 lags
# keeper 3 lag
# draft value 3 lag

colnames(model_data)
model_data %<>%
  select(1,2,5,8,9,10,11,12,13,14,19,20,21,25,26,27,28,35,36,37,38,45,46,47,48,55,56,57,58,59,60,61,62,72,73,74,75,76,77,78,79)
save(model_data, file = "/home/john/fantasy-football/modeling/model_data.Rda")
