---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(xgboost)
library(Hmisc)
load("/home/john/fantasy-football/data/analysis-data/wr.Rda")
load("/home/john/fantasy-football/data/analysis-data/wr_offense.Rda")
load("/home/john/fantasy-football/data/bn-draft-data/draft_data.Rda")
wr_model_data <- 
wr %>%
  filter(is.na(league_rank) == FALSE) %>%
  mutate(top40 = ifelse(league_rank <= 40,1,0),
         top20 = ifelse(league_rank <= 20,1,0),
         top10 = ifelse(league_rank <= 10,1,0),
         top5  = ifelse(league_rank <= 5,1,0)) %>%
  arrange(player,year) %>%
  group_by(player) %>%
  mutate(top40_lastyear = ifelse(lag(year) == year - 1, lag(top40),NA),
         top20_lastyear = ifelse(lag(year) == year - 1, lag(top20),NA),
         top10_lastyear = ifelse(lag(year) == year - 1, lag(top10),NA),
         top5_lastyear  = ifelse(lag(year) == year - 1, lag(top5),NA),
         team_rank_lastyear = ifelse(lag(year) == year - 1,lag(team_rank),NA),
         league_rank_lastyear = ifelse(lag(year) == year - 1,lag(league_rank),NA))
```


```{r}
head(draft_data)
```


```{r}
set.seed(2018)
labels <- c("top5","top10","top20","top40")
etas <- c(0.01,0.1,0.2,0.3)
depths <- c(1,2,4,8)

feature_names <- c("experience","age","top40_lastyear","top20_lastyear","top10_lastyear","top5_lastyear",
                                         "team_rank_lastyear","league_rank_lastyear")


models <- list()

counter <- 1
for(i in c(2010:2017)){
  models[[as.character(i)]] <- list()

  for(j in seq_along(labels)){
    models[[as.character(i)]][[labels[j]]] <- list()
    model_counter <- 1
    model_data <- wr_model_data %>% 
      ungroup() %>%
      filter(year < i, experience != 0) %>%
      select(year,top5,top10,top20,top40,experience,age,top40_lastyear,top20_lastyear,top10_lastyear,top5_lastyear,
                                         team_rank_lastyear,league_rank_lastyear) %>%
      as.matrix()

    ix <- sample(c(0,1), dim(model_data)[1], replace = TRUE, prob = c(1/3,2/3)) 

    dtrain <- xgb.DMatrix(model_data[ix==1,c(feature_names)],
                          label=model_data[ix == 1, labels[j]])
    dtest <- xgb.DMatrix(model_data[ix==0,c(feature_names)],
                         label=model_data[ix == 0,labels[j]])
    watchlist <- list(train=dtrain, test=dtest)

    for(k in seq_along(etas)){
      for(l in seq_along(depths)){
           models[[as.character(i)]][[labels[[j]]]][[model_counter]] <- 
            xgb.train(data = dtrain,
                      max.depth = depths[l], 
                      eta = etas[k],
                      nrounds = 1000, 
                      watchlist = watchlist,
                      eval.metric = "logloss",
                      early_stopping_rounds = 5,
                      gamma = 0.00001,
                      objective = "binary:logistic",
                      verbose = 0)
     
          model_counter <- model_counter + 1

      }
    }
  }
}
```

```{r}

all_predictions <- list()

for(i in c(2010:2017)){
  
  pred_data <-
    wr_model_data %>%
    filter(year == i) %>%
    ungroup() %>%
    select(year,top5,top10,top20,top40,experience,age,top40_lastyear,top20_lastyear,top10_lastyear,top5_lastyear,
                                           team_rank_lastyear,league_rank_lastyear) %>%
                    as.matrix()
  
  name <- wr_model_data %>%
        ungroup() %>%
        filter(year == i) %>%
        pull(name) 
  
  preds <- list()
  
  for(j in seq_along(labels)){
    best_ix <- which.min(lapply(models[[as.character(i)]][[labels[j]]],"[[","best_score"))
    preds[[j]] <- predict(models[[as.character(i)]][[labels[j]]][[best_ix]], pred_data[,c(feature_names)])            
  }
  
  all_predictions[[i-2009]] <-
    tibble(name = name,
           year = i,
           p5 = preds[[1]],
           p10 = preds[[2]],
           p20 = preds[[3]],
           p40 = preds[[4]])
  rm(preds,name,pred_data)
  
}
```

```{r}
all_predictions <- do.call(rbind,all_predictions)
all_predictions
```

Model Calibration

```{r}

calibration_data <-
  all_predictions %>% 
  left_join(wr_model_data, by = c("year","name")) %>%
  mutate(p5_bin = cut2(x = p5,
                       cuts = seq(from = 0, to = 1, by = 0.1)),
         p10_bin = cut2(x = p10,
                        cuts = seq(from = 0, to = 1, by = 0.1)),
         p20_bin = cut2(x = p20,
                        cuts = seq(from = 0, to = 1, by = 0.1)),
         p40_bin = cut2(x = p40,
                        cuts = seq(from = 0, to = 1, by = 0.1)))
head(calibration_data)
```

```{r}
calibration_data %>%
  group_by(p5_bin)  %>%
  summarise(total = n(),
            prop = sum(top5)/n())
```

```{r}
calibration_data %>%
  group_by(p10_bin)  %>%
  summarise(total = n(),
            prop = sum(top10)/n())
```

```{r}
calibration_data %>%
  group_by(p20_bin)  %>%
  summarise(total = n(),
            prop = sum(top20)/n())
```

```{r}
calibration_data %>%
  group_by(p40_bin)  %>%
  summarise(total = n(),
            prop = sum(top40)/n())
```



Desired Output Dataset


| Player | Year | Cost | P(top5) | top5 | P(top10) | top10 | P(top20) | top20 | P(top40) | top 40 |
|--------|------|------|---------|------|----------|-------|----------|-------|----------|--------|






Draft data. 

```{r}
wr_draft_data <- draft_data %>%
  filter(pos == 'WR') %>%
  select(player,year,keeper,adj_value)
wr_draft_data
```

top 5/10/20/40

```{r}
top_data <- wr_model_data %>%
  select(player,name,year,top5,top10,top20,top40)
```


Predictions for top 5/10/20/40

```{r}
analysis_data <-
  all_predictions %>%
  left_join(top_data, by = c("name","year")) %>%
  left_join(wr_draft_data, by = c("name" = "player","year")) %>%
  mutate(cost_bin = case_when(is.na(adj_value) ~ 'Undrafted',
                              adj_value == 1 ~ "$1",
                              adj_value >  1 & adj_value <= 5 ~ "$2 - $5",
                              adj_value >  5 & adj_value <= 15 ~ "$6 - $15",
                              adj_value > 15 & adj_value <= 25 ~ "$16 - $25",
                              adj_value > 25 & adj_value <= 35 ~ "$26 - $35",
                              adj_value > 35 & adj_value <= 50 ~ "$35 - $50",
                              adj_value > 50 & adj_value <= 75 ~ "$51 - $75",
                              adj_value > 75 ~ "$75+",
                              TRUE ~ as.character(NA)))
```


```{r}
analysis_data %>%
  filter(year == 2017)
```


```{r}
analysis_data %>%
  group_by(year,cost_bin) %>%
  arrange(year,cost_bin,desc(p20)) %>%
  filter(keeper != 1, year == 2016) %>%
  View()
```

