library(shiny)
library(gridExtra)

shinyUI(fluidPage(
            titlePanel("Bad Newz Realtime Draft Optimizer"),            
            # Create a new Row in the UI for selectInputs
            fluidRow(
              tabsetPanel(
                id = "inputs",
                tabPanel("My Roster",
                         column(2,
                                numericInput("budget", 
                                             label = h5("Budget"), 
                                             value = 292),
                                numericInput("qbs_needed",
                                             label = h5("QBs Needed"),
                                             value = 2),
                                numericInput("rbs_needed",
                                             label = h5("RBs Needed"),
                                             value = 2),
                                numericInput("wrs_needed",
                                             label = h5("WRs Needed"),
                                             value = 3),
                                numericInput("tes_needed",
                                             label = h5("TEs Needed"),
                                             value = 1))),
                tabPanel("QBs Available",
                         column(2,
                                numericInput("qb_cluster1", 
                                            label = h5("Cluster 1"),
                                            value = 3),
                                numericInput("qb_cluster2",
                                             label = h5("Cluster 2"),
                                             value = 4),
                                numericInput("qb_cluster3",
                                             label = h5("Cluster 3"),
                                             value = 7),
                                numericInput("qb_cluster4",
                                             label = h5("Cluster 4"),
                                             value = 6),
                                numericInput("qb_cluster5",
                                             label = h5("Cluster 5"),
                                             value = 8)
                                             )),
                tabPanel("RBs Available",
                         column(2,
                                numericInput("rb_cluster1", 
                                             label = h5("Cluster 1"),
                                             value = 3),
                                numericInput("rb_cluster2",
                                             label = h5("Cluster 2"),
                                             value = 3),
                                numericInput("rb_cluster3",
                                             label = h5("Cluster 3"),
                                             value = 4),
                                numericInput("rb_cluster4",
                                             label = h5("Cluster 4"),
                                             value = 4),
                                numericInput("rb_cluster5",
                                             label = h5("Cluster 5"),
                                             value = 4),
                                numericInput("rb_cluster6", 
                                             label = h5("Cluster 6"),
                                             value = 4),
                                numericInput("rb_cluster7",
                                             label = h5("Cluster 7"),
                                             value = 5),
                                numericInput("rb_cluster8",
                                             label = h5("Cluster 8"),
                                             value = 7),
                                numericInput("rb_cluster9",
                                             label = h5("Cluster 9"),
                                             value = 10),
                                numericInput("rb_cluster10",
                                             label = h5("Cluster 10"),
                                             value = 16))
              ),
              tabPanel("WRs Available",
                       column(2,
                              numericInput("wr_cluster1", 
                                           label = h5("Cluster 1"),
                                           value = 3),
                              numericInput("wr_cluster2",
                                           label = h5("Cluster 2"),
                                           value = 3),
                              numericInput("wr_cluster3",
                                           label = h5("Cluster 3"),
                                           value = 4),
                              numericInput("wr_cluster4",
                                           label = h5("Cluster 4"),
                                           value = 5),
                              numericInput("wr_cluster5",
                                           label = h5("Cluster 5"),
                                           value = 4),
                              numericInput("wr_cluster6", 
                                           label = h5("Cluster 6"),
                                           value = 7),
                              numericInput("wr_cluster7",
                                           label = h5("Cluster 7"),
                                           value = 6),
                              numericInput("wr_cluster8",
                                           label = h5("Cluster 8"),
                                           value = 6),
                              numericInput("wr_cluster9",
                                           label = h5("Cluster 9"),
                                           value = 9),
                              numericInput("wr_cluster10",
                                           label = h5("Cluster 10"),
                                           value = 12))
              ),
            tabPanel("TEs Available",
                     column(2,
                            numericInput("te_cluster1", 
                                         label = h5("Cluster 1"),
                                         value = 2),
                            numericInput("te_cluster2",
                                         label = h5("Cluster 2"),
                                         value = 3),
                            numericInput("te_cluster3",
                                         label = h5("Cluster 3"),
                                         value = 7),
                            numericInput("te_cluster4",
                                         label = h5("Cluster 4"),
                                         value = 4),
                            numericInput("te_cluster5",
                                         label = h5("Cluster 5"),
                                         value = 4)
            )))),
            # Create a new row for the output and recommendations
            fluidRow(
                tabsetPanel(
                id = 'dataset',
                tabPanel('Optimal Model', dataTableOutput('table_solution_model')),
                tabPanel('Total Spend', dataTableOutput('total_spend'))))

))
