---
title: "QB Fantasy Points as a function of PY, PTD, PINT, RY, RTD, FMBL"
output: html_notebook
---

```{r}
library(tidyverse)
library(lubridate)
library(DBI)
library(pool)
```


```{r}
pool <- dbPool(drv = RMySQL::MySQL(), 
               dbname = "armchair_analysis", 
               host = "localhost", 
               username = "john", 
               port = 3306, 
               unix.sock = "/var/run/mysqld/mysqld.sock")
team_name_abbr_lookup <- data.frame(abbr = c('ARI','ATL','BAL','BUF','CAR','CHI','CIN','CLE','DAL','DEN',
                                             'DET','GB' ,'HOU','IND','JAC','KC' ,'LA' ,'MIA','MIN','NE',
                                             'NO' ,'NYG','NYJ','OAK','PHI','PIT','SD' ,'SEA','SF' , 'STL',
                                             'TB','TEN','WAS'),
                                    name = c('Cardinals','Falcons','Ravens','Bills','Panthers','Bears','Bengals','Browns',
                                             'Cowboys','Broncos','Lions','Packers','Texans','Colts','Jaguars','Chiefs','Rams',
                                             'Dolphins','Vikings','Patriots','Saints','Giants','Jets','Raiders','Eagles',
                                             'Steelers','Chargers','Seahawks','49ers','Rams','Buccaneers','Titans','Redskins'),
                                    stringsAsFactors = FALSE)

offense <- dbGetQuery(con = pool,
                      "SELECT 
                      a.player
                      , b.wk as week
                      , a.year
                      , a.team
                      , 0.04*py + -2*ints + 4*tdp + 0.1*ry + 0.1*recy + 6*tdr + 6*tdrec -2*fuml +6*tdret as fp
                      ,py
                      ,ints
                      ,tdp
                      ,ry
                      ,recy
                      ,tdr
                      ,tdrec
                      ,fuml
                      ,tdret
                      FROM offense as a
                      JOIN game as b on a.gid = b.gid") 


two_point <- dbGetQuery(con = pool,
                        "select 
                        a.*
                        , b.gid
                        , c.seas as year
                        , c.wk as week 
                        from conv as a 
                        join play as b on a.pid = b.pid
                        join game as c on b.gid = c.gid where conv = 1")


rush_two_point <- two_point %>%
  filter(bc != "")
pass_two_point <- two_point %>%
  filter(psr != "")
two_point %>%
  filter(bc == "", psr == "") # forget this one


offense2 <-
  offense %>%
  left_join(., 
            pass_two_point %>% group_by(week,year,psr) %>% summarise(count = n()), 
            by = c("year","week","player" = "psr")) %>% 
  mutate(fp = ifelse(is.na(count) == FALSE, fp + 2*count, fp)) %>%
  select(-count)

offense3 <-
  offense2 %>%
  left_join(.,
            pass_two_point %>% group_by(week,year,trg) %>% summarise(count= n()),
            by = c("year","week","player" = "trg")) %>%
  mutate(fp = ifelse(is.na(count) == FALSE, fp+2*count, fp)) %>%
  select(-count)

offense4 <-
  offense3 %>%
  left_join(.,
            rush_two_point %>% group_by(week,year,bc) %>% summarise(count = n()),
            by = c("year","week","player" = "bc")) %>%
  mutate(fp = ifelse(is.na(count) == FALSE, fp+2*count, fp)) %>%
  select(-count)

# offense5 <- offense4 %>%
#   select(player,year,week,team,fp) %>%
#   rename(points = fp)

# Need names, teams, positions
qbs <- dbGetQuery(con = pool,
                  "select 
                  a.player
                  , a.fname
                  , a.lname
                  , a.dob
                  , a.start
                  from player as a
                  where pos1 = 'QB'")

qb_offense <- inner_join(qbs,offense4,by='player') %>% mutate(name = paste0(fname," ",lname),
                                                              experience = year - start,
                                                              age = year - year(as_date(dob)))
```

```{r}
head(qb_offense)
```

```{r}
glimpse(qb_offense)
```


```{r}
qb_summary <- 
qb_offense %>%
  filter(week <= 16) %>%
  group_by(player,fname,lname,year) %>%
  summarise(total_fp = sum(fp),
            total_py = sum(py),
            total_ints = sum(ints),
            total_tdp = sum(tdp),
            total_ry = sum(ry),
            total_recy = sum(recy),
            total_tdr = sum(tdr),
            total_tdrec = sum(tdrec))
```


```{r}
ggplot(data = qb_summary,
       aes(x = total_py, y = total_fp)) +
  geom_point() +
  geom_smooth()
```

```{r}
ggplot(data = qb_summary,
       aes(x = total_tdp, y = total_fp)) +
  geom_point() +
  geom_smooth()
```

```{r}
ggplot(data = qb_summary,
       aes(x = total_ints, y = total_fp)) +
  geom_point() +
  geom_smooth()
```

```{r}
fp_percent <- 
qb_summary %>%
  mutate(fp_py = 0.04*total_py,
         fp_ptd = 4*total_tdp) %>%
  mutate(pct_py = fp_py/total_fp,
         pct_ptd = fp_ptd/total_fp)
```

```{r}
ggplot(data = fp_percent %>% filter(pct_py >= 0, pct_py <= 1),
       aes(x = pct_py,
           y = total_fp)) +
  geom_point() +
  geom_smooth()
```
```{r}
ggplot(data = fp_percent %>% filter(pct_ptd >= 0, pct_ptd <= 1),
       aes(x = pct_ptd,
           y = total_fp)) +
  geom_point() +
  geom_smooth()
```

## Let's make this different, look at top 10 vs. not top 10 QBs...

```{r}
fp_percent_top10 <-
  fp_percent %>%
  group_by(year) %>%
  arrange(desc(total_fp)) %>%
  mutate(rank = row_number()) %>%
  mutate(top10 = ifelse(rank <= 10,1,0))
```

Re do the plots

```{r}
ggplot(data = fp_percent_top10 %>% filter(pct_py >= 0, pct_py <= 1),
       aes(x = pct_py,
           y = total_fp,
           group = top10,
           colour = top10)) +
  geom_point() +
  geom_smooth()
```

```{r}
ggplot(data = fp_percent_top10 %>% filter(pct_ptd >= 0, pct_ptd <= 1),
       aes(x = pct_ptd,
           y = total_fp,
           group = top10,
           colour = top10)) +
  geom_point() +
  geom_smooth()
```

```{r}
fp_percent_top10 %>%
  group_by(top10) %>%
  summarise(mean_pct_ptd = mean(pct_ptd),
            mean_pct_py = mean(pct_py))
```

top 10 QBs get 40% of their points from touchdowns, and 58% from py. 

```{r}
by_player <- 
fp_percent_top10 %>%
  group_by(fname,lname,top10) %>%
  summarise(total = n(),
            mean_pct_ptd = mean(pct_ptd),
           mean_pct_py = mean(pct_py))
```


```{r}
head(by_player)
```

```{r}

```

```{r}
ggplot(data = fp_percent_top10 %>% filter(pct_ptd >= 0, pct_ptd <= 1,
                                          pct_py >= 0, pct_py <= 1,
                                          total_fp > 100),
       aes(x = pct_ptd,
           y = pct_py,
           group = top10,
           shape = as.factor(top10),
           colour = total_fp)) +
  geom_point() +
  geom_smooth()
```

