---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
load("/home/john/fantasy-football/data/analysis-data/wr.Rda")
load("/home/john/fantasy-football/data/analysis-data/wr_offense.Rda")
```



```{r}
head(wr)
```

```{r}
d <- wr %>% filter(year == 2011)

k1 <- kmeans(d$total_points, 2, nstart = 20)
str(k1)
407594/553480
k1$betweenss/k1$totss


k1$cluster
d$cluster <- k1$cluster

d %>%
  group_by(cluster) %>%
  summarise(count = n(),
            mean_points = mean(total_points)) %>%
  arrange(desc(mean_points)) %>%
  mutate(tier = row_number())



```


Want to find tiers or WR total points

```{r}

d <- wr %>% filter(year == 2011) %

k1 <- kmeans(d$total_points, 2, nstart = 20)
str(k1)
407594/553480
k1$betweenss/k1$totss

m <- matrix(0,nrow = 9*17,ncol = 3)
output <- list()
counter <- 1
for(y in c(2001:2017)){
  
  d <- wr %>% filter(year == y,
                     league_rank <= 40)
  print(max(d$year))
  for(centers in c(2:10)){
  
    k <- kmeans(d$total_points,centers,nstart = 20)
    
    d$cluster <- k$cluster
    
    output[[counter]] <- list()
    output[[counter]] <- d %>%
      group_by(cluster) %>%
      summarise(count = n(),
                mean_points = mean(total_points)) %>%
      arrange(desc(mean_points)) %>%
      mutate(tier = row_number())
    
    m[counter,] <- c(y,centers,k$betweenss/k$totss)
  
    counter <- counter+1
    
    rm(k)
  }
}


```

```{r}
for(y in c(2001:2017)){
  plot <-
  ggplot(data = m %>% as.data.frame() %>% filter(V1 == y),
         aes(x = V2, y = V3)) +
    geom_point() +
    geom_line() +
    ggtitle(paste0("Year ",as.character(y)))
  print(plot)
  rm(plot)
}
```

```{r}
m %>% as.data.frame() %>%
  group_by(V2) %>%
  summarise(mean_r2 = mean(V3)) %>%
  ggplot(data = .,
         aes(x = V2, y = mean_r2)) +
  geom_point() +
  geom_line()
```

```{r}
m %>% as.data.frame() %>%
  group_by(V2) %>%
  summarise(mean_r2 = mean(V3))
```

```{r}
m %>% 
  as.data.frame() %>%
  group_by(V2) %>%
  summarise(mean_r2 = mean(V3),
            se = sd(V3)/n()) %>%
  ggplot(., 
         aes(x=V2, y=mean_r2)) + 
  geom_bar(stat="identity") +
  geom_errorbar(aes(ymin = mean_r2-2*se,
                    ymax = mean_r2+2*se)) +
  scale_x_continuous(breaks = c(2:10))


```

Go with 5 groups
5 groups are the 4th, 13th, 22nd, etc.

```{r}
ix <- seq(from = 4, to = 4 +17*9, by = 9)

output[ix]

five_groups <- do.call(rbind,output[ix])
five_groups$year <- rep(c(2001:2017),each = 5)

ggplot(data = five_groups,
       aes(x = as.factor(tier), y = mean_points)) +
  geom_boxplot() +
  geom_point()

```
```{r}
fit <- lm(data = five_groups,
   mean_points ~ tier + year + tier*year)
summary(fit)

fit2 <- lm(data = five_groups,
           mean_points ~ tier + year)
summary(fit2)

ggplot(data = five_groups,
       aes(x = year, y = mean_points, group = tier, colour = as.factor(tier))) +
  geom_point() +
  geom_line() +
  geom_smooth()
```


```{r}
ggplot(data = five_groups,
       aes(x = year, y = count, group = tier, colour = as.factor(tier))) +
  geom_point() +
  geom_line() +
  geom_smooth()
```

